-- ============================================================
-- MIGRATION: categories/board_category -> tiles/board_layouts
-- Big-bang, no compatibility layer
-- Based on current production metadata (no assumptions)
-- ============================================================

BEGIN;

-- 1) Rename core tables
ALTER TABLE public.categories RENAME TO tiles;
ALTER TABLE public.board_category RENAME TO board_layouts;

-- 2) Rename relationship columns
ALTER TABLE public.questions RENAME COLUMN category_id TO tile_id;
ALTER TABLE public.board_layouts RENAME COLUMN category_id TO tile_id;

-- 3) Rename existing constraints to final naming
ALTER TABLE public.questions
  RENAME CONSTRAINT questions_category_id_fkey TO questions_tile_id_fkey;

ALTER TABLE public.board_layouts
  RENAME CONSTRAINT board_category_category_id_fkey TO board_layouts_tile_id_fkey;

ALTER TABLE public.board_layouts
  RENAME CONSTRAINT board_category_board_id_fkey TO board_layouts_board_id_fkey;

ALTER TABLE public.tiles
  RENAME CONSTRAINT categories_pkey TO tiles_pkey;

ALTER TABLE public.tiles
  RENAME CONSTRAINT categories_name_user_id_key TO tiles_name_user_id_key;

ALTER TABLE public.board_layouts
  RENAME CONSTRAINT board_category_pkey TO board_layouts_pkey;

ALTER TABLE public.board_layouts
  RENAME CONSTRAINT valid_square_position TO board_layouts_valid_position;

-- 4) Rename indexes generated by PK/UNIQUE constraints
ALTER INDEX IF EXISTS public.categories_pkey RENAME TO tiles_pkey;
ALTER INDEX IF EXISTS public.categories_name_user_id_key RENAME TO tiles_name_user_id_key;
ALTER INDEX IF EXISTS public.board_category_pkey RENAME TO board_layouts_pkey;

-- 5) Recreate RLS policies with new naming and same logic
DROP POLICY IF EXISTS "Los profesores gestionan sus propias categorías" ON public.tiles;
DROP POLICY IF EXISTS "Los profesores gestionan el layout de sus tableros" ON public.board_layouts;
DROP POLICY IF EXISTS "Los profesores gestionan sus propias preguntas" ON public.questions;

CREATE POLICY "Los profesores gestionan sus propios tiles"
ON public.tiles
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Los profesores gestionan el layout de sus tableros"
ON public.board_layouts
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.boards
    WHERE boards.id = board_layouts.board_id
      AND boards.user_id = auth.uid()
  )
);

CREATE POLICY "Los profesores gestionan sus propias preguntas"
ON public.questions
FOR ALL
USING (auth.uid() = user_id);

-- Keep RLS enabled
ALTER TABLE public.tiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_layouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

COMMIT;
